apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: tjaeger@redhat.com
    serving.knative.dev/lastModifier: tjaeger@redhat.com
  creationTimestamp: "2021-04-15T16:27:16Z"
  generation: 1
  managedFields:
  - apiVersion: serving.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:template:
          .: {}
          f:metadata:
            .: {}
            f:annotations:
              .: {}
              f:client.knative.dev/user-image: {}
            f:creationTimestamp: {}
            f:name: {}
          f:spec:
            .: {}
            f:containers: {}
    manager: kn
    operation: Update
    time: "2021-04-15T16:27:16Z"
  - apiVersion: serving.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:address:
          .: {}
          f:url: {}
        f:conditions: {}
        f:latestCreatedRevisionName: {}
        f:latestReadyRevisionName: {}
        f:observedGeneration: {}
        f:traffic: {}
        f:url: {}
    manager: controller
    operation: Update
    time: "2021-04-15T16:27:35Z"
  name: event-display
  namespace: greeting
  resourceVersion: "595698406"
  selfLink: /apis/serving.knative.dev/v1/namespaces/greeting/services/event-display
  uid: 4da9a0b8-3644-4f19-a5a4-72e15d0e0540
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest
      creationTimestamp: null
      name: event-display-xsgcr-1
    spec:
      containerConcurrency: 0
      containers:
      - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: http://event-display.greeting.svc.cluster.local
  conditions:
  - lastTransitionTime: "2021-04-15T16:27:36Z"
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: "2021-04-15T16:27:37Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-04-15T16:27:37Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: event-display-xsgcr-1
  latestReadyRevisionName: event-display-xsgcr-1
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: event-display-xsgcr-1
  url: http://event-display-greeting.apps.cligg.me
